### ISSUE TITLE
Channel Reconfiguration

### ISSUE THREAD

**Issue by nMaroulis** [5g-empower/empower-runtime#17]
Hi,
Is it possible to change the channel of the WTPs in real time from the controller. Something like:
for block in  wtp.supports:
  block.channel = 11
, thus triggering a channel change in the WTPs??

Thank you in advance.

**Comment by rriggio** [comment]
This feature is coming soon to the opensource version. Stay tuned.

**Comment by rriggio** [comment]
empower now supports Channel Switching Announcement, which means that you can do handovers between WTP with different channels. However we decided not to support setting a new channel from the Empower API because we believe that setting the channel is part of the pre-configuration, for example it would not make sense that a particular virtual network can change the channel of the AP.
