### ISSUE TITLE
UEs not appearing in 5G-EmPOWER Web Interface and not possible to attribute UEs to a slice via Web Interface

### ISSUE THREAD

**Issue by branchereaua** [5g-empower/empower-runtime#173]
Hello,

We are trying to setup 5G-EmPOWER and perform LTE RAN slicing.
Our configuration is based on srsENB and srsEPC (20.04.2).

We have successfully connected different COTS UEs (Honor View20, LG Nexus 5, Motorola Moto G 4G) to srsLTE and they have access to the Internet.

After creating a project in the Empower-runtime Web Interface, we wanted to attribute UEs to different slices.
But we faced 2 issues:

1. Connected UEs doesn't appear in the Clients > UEs section, except for the LG Nexus 5

2. From the project page, we can manage slices (creation, modification,...) but we didn't manage to find how to attribute UEs to a specific slice.

Could you please help us to overcome these issues?

Best regards,
Alan B. & Ehsan EK.

**Comment by rriggio** [comment]
Regarding point (1) this must be due to the fact that empower asks the UE identity, meaning the IMSI. If the UE does not provide it then the UE is not added to the controller. Regarding point (2) the support for slicing is not available for the open-source version. A new version could be available in the future but for now, if you are interested please contact me via email.

**Comment by branchereaua** [comment]
Thank you for your response.

Regarding point (1), the UEs are correctly sending their IMSI because srsENB and srsEPC are able to see them. So I don't think the issue is coming from the UE identity side. For some reason the Agent correctly adds the Nexus 5 to the controller database after its connection, but not the other UEs.

Regarding LTE Slicing, do you mean that it is available under a commercial version ?

Best regards,
Alan B. & Ehsan EK.

**Comment by rriggio** [comment]
Hi,

the IMSI is obtained by the controller by forcing the eNB to send an
identity request message. According to the standard this message should be
sent only by the core network. Empower triggers this message and intercepts
the reply. It is possible that some UE refuse to reply with their IMSI.
However, since I only have a nexus 5 I do not have a way to test this.

Regarding point (2) we could in principle provide you with the lte slicing
feature under a commercial license if you are interested.

R.

**Comment by branchereaua** [comment]
Hi, thank you for your response.

Indeed, I think this is the reason why only the Nexus 5 can be added to the controller.
As can be seen in the attached PCAPs, the Nexus 5 sends an Identity Response, but the Honor View20 and The Motorola Moto G do not.
Do you think there is another way for the controller to obtain the IMSIs from UEs?

Best regards,
Alan B. & Ehsan EK.

**Comment by branchereaua** [comment]
Hi, thank you for your response.

Indeed, I think this is the reason why only the Nexus 5 can be added to the controller.
As can be seen in the attached PCAPs, the Nexus 5 sends an Identity Response, but the Honor View20 and The Motorola Moto G do not.
Do you think there is another way for the controller to obtain the IMSIs from UEs?

Best regards,
Alan B. & Ehsan EK.

[UEpcap.zip](https://github.com/5g-empower/empower-runtime/files/5530073/UEpcap.zip)

**Comment by rriggio** [comment]
I will check the pcaps, indeed without having the phones it is hard to make
trial. Maybe you can look into the code and see if you can find a
workaround. Another ID to use is the GUTI but I never looked at it. Meaning
I do not know if it can be collected. TMSI could also be a valid ID. The
RNTI is unstable because it can change very often.

**Comment by k20065133** [comment]
Hi:

I am trying to use 5G-EmPOWER to perform LTE RAN slicing. But I am facing the same issue, the UE does not appear in the UE list in the web interface. Is there any suggestion for that?

Thanks
Tony
